services:
  node:
    container_name: pi-be
    restart: always
    build: .
    ports: 
      - "8080:8080"
    links:
      - mongo
    volumes:
      - .:/usr/src/app
  mongo:
    container_name: mongoDB
    image: mongo
    ports:
      - "27017:27017"



